### PR TITLE
A few fixes in the build process

### PR DESCRIPTION
**Pull request by perror**
I noticed a few bugs after completing the build process, mainly:

- The `mountpoint/` directory was not created.

  I added a line that create it in the main `Makefile`.  The drawback is that some vm may not have `mountpoint/`.  But, in some way, they should always have one...

- The empty path `/home/user/` has been omitted by git as it is an empty directory (no file).

  I added a `/home/user/.profile` file (taken from `/etc/profile`) to force `git` to keep track of this path. The drawback is that an empty `/home/user` is surely better for what we need...

Feel free to comment on my fixes and propose some improvement if needed.

EDIT
----------------------------

I added a commit allowing to build multi-architecture VM. A few things about it:

- I am not sure that the `export` in `linux/Makefile` and `busybox/Makefile` are really necessary.
- I struggled a lot before noticing that `linux/build/arch/<ARCH>/boot/bzImage` was not a standard. In fact, it seems that each architecture has its own name for the image. For AArch64, the name is `Image.gz`. So, I added a shell variable that gives the name of the Image. But, it seems that, at the end, the `Image.gz` is copied to `build/vm` with the name `bzImage` finally. I do not know if we want change this.

Finally, note that the final vm in AArch64 is not working because the QEMU options are not right (but the build process goes fine all along). So, there is still work left!

### CODE REVIEW

**Review by t00sh — COMMENTED** [review]
Maybe the mountpoint should be created during the execution of start.sh script in templates. It makes the build process more generic.

**Comment by perror** [comment]
I agree, seems better to me. I changed the patches accordingly.
Tell me if you think about something else you want me to change.

**Comment by t00sh** [comment]
You probably forget to change the `./templates/aarch/start.sh` script. You should replace the `qemu-system-x86_64` and add `-machine` option.

And did you test the aarch64 virtual machine ? On my side, qemu don't want to launch generated VM.

Finally, new variables should be tested with `check_defined` function before using it.

**Comment by perror** [comment]
> You probably forget to change the ./templates/aarch/start.sh script. You should replace the qemu-system-x86_64 and add -machine option.

Augh, I did modify the `start.sh` script which was in `build/` and not the original one... But, I cannot reach a set of options that makes the machine run properly.

> And did you test the aarch64 virtual machine ? On my side, qemu don't want to launch generated VM.

Same... I miss a PCI bus somehow.

> Finally, new variables should be tested with check_defined function before using it.

Ah, at first I did think it was possible to have these variables as optional, so I did not check it after I realized it was not an option. But, this is still optional for `CONF_CROSS_COMPILE_PREFIX`.

I changed it for the `CONF_LINUX_ARCH` and `CONF_BUSYBOX_ARCH`.

**Comment by perror** [comment]
Okay, I had several problems with the multiarch build. So, I decided to make it in a separate branch (sorry, I am discovering the github workflow). I will work a bit deeper in the multiarch branch and make a pull request when it will be working.

**Comment by t00sh** [comment]
Thanks, I merged your pull request !

**Pull request merged**
