### PR TITLE
Multiarch and few other things

### PR DESCRIPTION
**Pull request by perror**
I added:

- An 'hopefully' stable way to handle cross-compilation and multiarch in the scripts.
- A first working example with i386 architecture (not much because it is very close to amd64).
- A few modifications to bypass the download of the kernel sources and allow to provide its own linux kernel source archives (with its own patches applied).

Right now, I am working on a Linux VM which will have the dirtyc0w security flaw to try out a few things. It build perfectly but I cannot trigger the dirtyc0w problem yet. I need a bit more time to finish.

### CODE REVIEW

**Comment by perror** [comment]
Okay, this is coming to something now! I have some faith in the fact the whole framework can work without any custom tweaks and be portable.

Still, code may be improved, but at least I reached something that works (hopefully).

**Comment by t00sh** [comment]
Is it possible to remove commits related to Dirty Cow vulnerability for the current pull request ?
The goal of this repository was originally to propose a simple way to build small virtual machines for multiple architectures.

Moreover, a separate repository for this kind of templates could be a nice idea.

**Comment by perror** [comment]
Done! The 'dirtyc0w' patch has been put aside in another branch. Should be ready for merge.

**Comment by t00sh** [comment]
Merged. Thanks for the patch !

**Pull request merged**
